name: Generate Snake

on:
  schedule: # Executa automaticamente 1x por dia
    - cron: "0 0 * * *"
  workflow_dispatch: # permite rodar manualmente pelo Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera os gráficos do Snake/Pac-Man
      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: dcVictor
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg
            dist/pacman-contribution-graph.gif
            dist/pacman-contribution-graph-dark.gif

      # Faz o push para a branch `output`
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
